oidc:
  enabled: false
  cache-tokens: true
  iam-properties:
    "[https://iam-test.indigo-datacloud.eu/]":
      orchestrator:
        client-id: <clientID>
        client-secret: <clientSecret>
        scopes: [openid, profile, offline_access]
      clues:
        client-id: <clientID>
        client-secret: <clientSecret>