/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.reply.orchestrator.dto.kubernetes.fluxcd;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The reference to an external source with release values.
 */
@ApiModel(description = "The reference to an external source with release values.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-16T10:28:05.581Z[Etc/UTC]")
public class V1HelmReleaseSpecExternalSourceRef {
  public static final String SERIALIZED_NAME_OPTIONAL = "optional";
  @SerializedName(SERIALIZED_NAME_OPTIONAL)
  private Boolean optional;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;


  public V1HelmReleaseSpecExternalSourceRef optional(Boolean optional) {
    
    this.optional = optional;
    return this;
  }

   /**
   * Optional will mark this ExternalSourceSelector as optional. The result of this are that operations are permitted without the source, due to it e.g. being temporarily unavailable.
   * @return optional
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional will mark this ExternalSourceSelector as optional. The result of this are that operations are permitted without the source, due to it e.g. being temporarily unavailable.")

  public Boolean getOptional() {
    return optional;
  }


  public void setOptional(Boolean optional) {
    this.optional = optional;
  }


  public V1HelmReleaseSpecExternalSourceRef url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * URL is the URL of the external source.
   * @return url
  **/
  @ApiModelProperty(required = true, value = "URL is the URL of the external source.")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1HelmReleaseSpecExternalSourceRef v1HelmReleaseSpecExternalSourceRef = (V1HelmReleaseSpecExternalSourceRef) o;
    return Objects.equals(this.optional, v1HelmReleaseSpecExternalSourceRef.optional) &&
        Objects.equals(this.url, v1HelmReleaseSpecExternalSourceRef.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(optional, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1HelmReleaseSpecExternalSourceRef {\n");
    sb.append("    optional: ").append(toIndentedString(optional)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

