/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.reply.orchestrator.dto.kubernetes.fluxcd;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * V1HelmReleaseStatusConditions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-16T10:28:05.581Z[Etc/UTC]")
public class V1HelmReleaseStatusConditions {
  public static final String SERIALIZED_NAME_LAST_TRANSITION_TIME = "lastTransitionTime";
  @SerializedName(SERIALIZED_NAME_LAST_TRANSITION_TIME)
  private DateTime lastTransitionTime;

  public static final String SERIALIZED_NAME_LAST_UPDATE_TIME = "lastUpdateTime";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATE_TIME)
  private DateTime lastUpdateTime;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  private String reason;

  /**
   * Status of the condition, one of (&#39;True&#39;, &#39;False&#39;, &#39;Unknown&#39;).
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    TRUE("True"),
    
    FALSE("False"),
    
    UNKNOWN("Unknown");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  /**
   * Type of the condition, one of (&#39;ChartFetched&#39;, &#39;Deployed&#39;, &#39;Released&#39;, &#39;RolledBack&#39;, &#39;Tested&#39;).
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    CHARTFETCHED("ChartFetched"),
    
    DEPLOYED("Deployed"),
    
    RELEASED("Released"),
    
    ROLLEDBACK("RolledBack"),
    
    TESTED("Tested");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;


  public V1HelmReleaseStatusConditions lastTransitionTime(DateTime lastTransitionTime) {
    
    this.lastTransitionTime = lastTransitionTime;
    return this;
  }

   /**
   * LastTransitionTime is the timestamp corresponding to the last status change of this condition.
   * @return lastTransitionTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "LastTransitionTime is the timestamp corresponding to the last status change of this condition.")

  public DateTime getLastTransitionTime() {
    return lastTransitionTime;
  }


  public void setLastTransitionTime(DateTime lastTransitionTime) {
    this.lastTransitionTime = lastTransitionTime;
  }


  public V1HelmReleaseStatusConditions lastUpdateTime(DateTime lastUpdateTime) {
    
    this.lastUpdateTime = lastUpdateTime;
    return this;
  }

   /**
   * LastUpdateTime is the timestamp corresponding to the last status update of this condition.
   * @return lastUpdateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "LastUpdateTime is the timestamp corresponding to the last status update of this condition.")

  public DateTime getLastUpdateTime() {
    return lastUpdateTime;
  }


  public void setLastUpdateTime(DateTime lastUpdateTime) {
    this.lastUpdateTime = lastUpdateTime;
  }


  public V1HelmReleaseStatusConditions message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Message is a human readable description of the details of the last transition, complementing reason.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Message is a human readable description of the details of the last transition, complementing reason.")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public V1HelmReleaseStatusConditions reason(String reason) {
    
    this.reason = reason;
    return this;
  }

   /**
   * Reason is a brief machine readable explanation for the condition&#39;s last transition.
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Reason is a brief machine readable explanation for the condition's last transition.")

  public String getReason() {
    return reason;
  }


  public void setReason(String reason) {
    this.reason = reason;
  }


  public V1HelmReleaseStatusConditions status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Status of the condition, one of (&#39;True&#39;, &#39;False&#39;, &#39;Unknown&#39;).
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Status of the condition, one of ('True', 'False', 'Unknown').")

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public V1HelmReleaseStatusConditions type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type of the condition, one of (&#39;ChartFetched&#39;, &#39;Deployed&#39;, &#39;Released&#39;, &#39;RolledBack&#39;, &#39;Tested&#39;).
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Type of the condition, one of ('ChartFetched', 'Deployed', 'Released', 'RolledBack', 'Tested').")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1HelmReleaseStatusConditions v1HelmReleaseStatusConditions = (V1HelmReleaseStatusConditions) o;
    return Objects.equals(this.lastTransitionTime, v1HelmReleaseStatusConditions.lastTransitionTime) &&
        Objects.equals(this.lastUpdateTime, v1HelmReleaseStatusConditions.lastUpdateTime) &&
        Objects.equals(this.message, v1HelmReleaseStatusConditions.message) &&
        Objects.equals(this.reason, v1HelmReleaseStatusConditions.reason) &&
        Objects.equals(this.status, v1HelmReleaseStatusConditions.status) &&
        Objects.equals(this.type, v1HelmReleaseStatusConditions.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastTransitionTime, lastUpdateTime, message, reason, status, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1HelmReleaseStatusConditions {\n");
    sb.append("    lastTransitionTime: ").append(toIndentedString(lastTransitionTime)).append("\n");
    sb.append("    lastUpdateTime: ").append(toIndentedString(lastUpdateTime)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

