/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.reply.orchestrator.dto.kubernetes.fluxcd;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The rollback settings for this Helm release.
 */
@ApiModel(description = "The rollback settings for this Helm release.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-16T10:28:05.581Z[Etc/UTC]")
public class V1HelmReleaseSpecRollback {
  public static final String SERIALIZED_NAME_DISABLE_HOOKS = "disableHooks";
  @SerializedName(SERIALIZED_NAME_DISABLE_HOOKS)
  private Boolean disableHooks;

  public static final String SERIALIZED_NAME_ENABLE = "enable";
  @SerializedName(SERIALIZED_NAME_ENABLE)
  private Boolean enable;

  public static final String SERIALIZED_NAME_FORCE = "force";
  @SerializedName(SERIALIZED_NAME_FORCE)
  private Boolean force;

  public static final String SERIALIZED_NAME_MAX_RETRIES = "maxRetries";
  @SerializedName(SERIALIZED_NAME_MAX_RETRIES)
  private Long maxRetries;

  public static final String SERIALIZED_NAME_RECREATE = "recreate";
  @SerializedName(SERIALIZED_NAME_RECREATE)
  private Boolean recreate;

  public static final String SERIALIZED_NAME_RETRY = "retry";
  @SerializedName(SERIALIZED_NAME_RETRY)
  private Boolean retry;

  public static final String SERIALIZED_NAME_TIMEOUT = "timeout";
  @SerializedName(SERIALIZED_NAME_TIMEOUT)
  private Long timeout;

  public static final String SERIALIZED_NAME_WAIT = "wait";
  @SerializedName(SERIALIZED_NAME_WAIT)
  private Boolean wait;


  public V1HelmReleaseSpecRollback disableHooks(Boolean disableHooks) {
    
    this.disableHooks = disableHooks;
    return this;
  }

   /**
   * DisableHooks will mark this Helm release to prevent hooks from running during the rollback.
   * @return disableHooks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "DisableHooks will mark this Helm release to prevent hooks from running during the rollback.")

  public Boolean getDisableHooks() {
    return disableHooks;
  }


  public void setDisableHooks(Boolean disableHooks) {
    this.disableHooks = disableHooks;
  }


  public V1HelmReleaseSpecRollback enable(Boolean enable) {
    
    this.enable = enable;
    return this;
  }

   /**
   * Enable will mark this Helm release for rollbacks.
   * @return enable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Enable will mark this Helm release for rollbacks.")

  public Boolean getEnable() {
    return enable;
  }


  public void setEnable(Boolean enable) {
    this.enable = enable;
  }


  public V1HelmReleaseSpecRollback force(Boolean force) {
    
    this.force = force;
    return this;
  }

   /**
   * Force will mark this Helm release to &#x60;--force&#x60; rollbacks. This forces the resource updates through delete/recreate if needed.
   * @return force
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Force will mark this Helm release to `--force` rollbacks. This forces the resource updates through delete/recreate if needed.")

  public Boolean getForce() {
    return force;
  }


  public void setForce(Boolean force) {
    this.force = force;
  }


  public V1HelmReleaseSpecRollback maxRetries(Long maxRetries) {
    
    this.maxRetries = maxRetries;
    return this;
  }

   /**
   * MaxRetries is the maximum amount of upgrade retries the operator should make before bailing.
   * @return maxRetries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "MaxRetries is the maximum amount of upgrade retries the operator should make before bailing.")

  public Long getMaxRetries() {
    return maxRetries;
  }


  public void setMaxRetries(Long maxRetries) {
    this.maxRetries = maxRetries;
  }


  public V1HelmReleaseSpecRollback recreate(Boolean recreate) {
    
    this.recreate = recreate;
    return this;
  }

   /**
   * Recreate will mark this Helm release to &#x60;--recreate-pods&#x60; for if applicable. This performs pod restarts.
   * @return recreate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Recreate will mark this Helm release to `--recreate-pods` for if applicable. This performs pod restarts.")

  public Boolean getRecreate() {
    return recreate;
  }


  public void setRecreate(Boolean recreate) {
    this.recreate = recreate;
  }


  public V1HelmReleaseSpecRollback retry(Boolean retry) {
    
    this.retry = retry;
    return this;
  }

   /**
   * Retry will mark this Helm release for upgrade retries after a rollback.
   * @return retry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Retry will mark this Helm release for upgrade retries after a rollback.")

  public Boolean getRetry() {
    return retry;
  }


  public void setRetry(Boolean retry) {
    this.retry = retry;
  }


  public V1HelmReleaseSpecRollback timeout(Long timeout) {
    
    this.timeout = timeout;
    return this;
  }

   /**
   * Timeout is the time to wait for any individual Kubernetes operation (like Jobs for hooks) during rollback.
   * @return timeout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Timeout is the time to wait for any individual Kubernetes operation (like Jobs for hooks) during rollback.")

  public Long getTimeout() {
    return timeout;
  }


  public void setTimeout(Long timeout) {
    this.timeout = timeout;
  }


  public V1HelmReleaseSpecRollback wait(Boolean wait) {
    
    this.wait = wait;
    return this;
  }

   /**
   * Wait will mark this Helm release to wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful.
   * @return wait
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Wait will mark this Helm release to wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful.")

  public Boolean getWait() {
    return wait;
  }


  public void setWait(Boolean wait) {
    this.wait = wait;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1HelmReleaseSpecRollback v1HelmReleaseSpecRollback = (V1HelmReleaseSpecRollback) o;
    return Objects.equals(this.disableHooks, v1HelmReleaseSpecRollback.disableHooks) &&
        Objects.equals(this.enable, v1HelmReleaseSpecRollback.enable) &&
        Objects.equals(this.force, v1HelmReleaseSpecRollback.force) &&
        Objects.equals(this.maxRetries, v1HelmReleaseSpecRollback.maxRetries) &&
        Objects.equals(this.recreate, v1HelmReleaseSpecRollback.recreate) &&
        Objects.equals(this.retry, v1HelmReleaseSpecRollback.retry) &&
        Objects.equals(this.timeout, v1HelmReleaseSpecRollback.timeout) &&
        Objects.equals(this.wait, v1HelmReleaseSpecRollback.wait);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disableHooks, enable, force, maxRetries, recreate, retry, timeout, wait);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1HelmReleaseSpecRollback {\n");
    sb.append("    disableHooks: ").append(toIndentedString(disableHooks)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    force: ").append(toIndentedString(force)).append("\n");
    sb.append("    maxRetries: ").append(toIndentedString(maxRetries)).append("\n");
    sb.append("    recreate: ").append(toIndentedString(recreate)).append("\n");
    sb.append("    retry: ").append(toIndentedString(retry)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    wait: ").append(toIndentedString(wait)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

