/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.reply.orchestrator.dto.kubernetes.fluxcd;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The reference to a local chart file with release values.
 */
@ApiModel(description = "The reference to a local chart file with release values.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-16T10:28:05.581Z[Etc/UTC]")
public class V1HelmReleaseSpecChartFileRef {
  public static final String SERIALIZED_NAME_OPTIONAL = "optional";
  @SerializedName(SERIALIZED_NAME_OPTIONAL)
  private Boolean optional;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;


  public V1HelmReleaseSpecChartFileRef optional(Boolean optional) {
    
    this.optional = optional;
    return this;
  }

   /**
   * Optional will mark this ChartFileSelector as optional. The result of this are that operations are permitted without the source, due to it e.g. being temporarily unavailable.
   * @return optional
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional will mark this ChartFileSelector as optional. The result of this are that operations are permitted without the source, due to it e.g. being temporarily unavailable.")

  public Boolean getOptional() {
    return optional;
  }


  public void setOptional(Boolean optional) {
    this.optional = optional;
  }


  public V1HelmReleaseSpecChartFileRef path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * Path is the file path to the source relative to the chart root.
   * @return path
  **/
  @ApiModelProperty(required = true, value = "Path is the file path to the source relative to the chart root.")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1HelmReleaseSpecChartFileRef v1HelmReleaseSpecChartFileRef = (V1HelmReleaseSpecChartFileRef) o;
    return Objects.equals(this.optional, v1HelmReleaseSpecChartFileRef.optional) &&
        Objects.equals(this.path, v1HelmReleaseSpecChartFileRef.path);
  }

  @Override
  public int hashCode() {
    return Objects.hash(optional, path);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1HelmReleaseSpecChartFileRef {\n");
    sb.append("    optional: ").append(toIndentedString(optional)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

