/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.reply.orchestrator.dto.kubernetes.fluxcd;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * V1HelmReleaseSpecValuesFrom
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-16T10:28:05.581Z[Etc/UTC]")
public class V1HelmReleaseSpecValuesFrom {
  public static final String SERIALIZED_NAME_CHART_FILE_REF = "chartFileRef";
  @SerializedName(SERIALIZED_NAME_CHART_FILE_REF)
  private V1HelmReleaseSpecChartFileRef chartFileRef;

  public static final String SERIALIZED_NAME_CONFIG_MAP_KEY_REF = "configMapKeyRef";
  @SerializedName(SERIALIZED_NAME_CONFIG_MAP_KEY_REF)
  private V1HelmReleaseSpecConfigMapKeyRef configMapKeyRef;

  public static final String SERIALIZED_NAME_EXTERNAL_SOURCE_REF = "externalSourceRef";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_SOURCE_REF)
  private V1HelmReleaseSpecExternalSourceRef externalSourceRef;

  public static final String SERIALIZED_NAME_SECRET_KEY_REF = "secretKeyRef";
  @SerializedName(SERIALIZED_NAME_SECRET_KEY_REF)
  private V1HelmReleaseSpecSecretKeyRef secretKeyRef;


  public V1HelmReleaseSpecValuesFrom chartFileRef(V1HelmReleaseSpecChartFileRef chartFileRef) {
    
    this.chartFileRef = chartFileRef;
    return this;
  }

   /**
   * Get chartFileRef
   * @return chartFileRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1HelmReleaseSpecChartFileRef getChartFileRef() {
    return chartFileRef;
  }


  public void setChartFileRef(V1HelmReleaseSpecChartFileRef chartFileRef) {
    this.chartFileRef = chartFileRef;
  }


  public V1HelmReleaseSpecValuesFrom configMapKeyRef(V1HelmReleaseSpecConfigMapKeyRef configMapKeyRef) {
    
    this.configMapKeyRef = configMapKeyRef;
    return this;
  }

   /**
   * Get configMapKeyRef
   * @return configMapKeyRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1HelmReleaseSpecConfigMapKeyRef getConfigMapKeyRef() {
    return configMapKeyRef;
  }


  public void setConfigMapKeyRef(V1HelmReleaseSpecConfigMapKeyRef configMapKeyRef) {
    this.configMapKeyRef = configMapKeyRef;
  }


  public V1HelmReleaseSpecValuesFrom externalSourceRef(V1HelmReleaseSpecExternalSourceRef externalSourceRef) {
    
    this.externalSourceRef = externalSourceRef;
    return this;
  }

   /**
   * Get externalSourceRef
   * @return externalSourceRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1HelmReleaseSpecExternalSourceRef getExternalSourceRef() {
    return externalSourceRef;
  }


  public void setExternalSourceRef(V1HelmReleaseSpecExternalSourceRef externalSourceRef) {
    this.externalSourceRef = externalSourceRef;
  }


  public V1HelmReleaseSpecValuesFrom secretKeyRef(V1HelmReleaseSpecSecretKeyRef secretKeyRef) {
    
    this.secretKeyRef = secretKeyRef;
    return this;
  }

   /**
   * Get secretKeyRef
   * @return secretKeyRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1HelmReleaseSpecSecretKeyRef getSecretKeyRef() {
    return secretKeyRef;
  }


  public void setSecretKeyRef(V1HelmReleaseSpecSecretKeyRef secretKeyRef) {
    this.secretKeyRef = secretKeyRef;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1HelmReleaseSpecValuesFrom v1HelmReleaseSpecValuesFrom = (V1HelmReleaseSpecValuesFrom) o;
    return Objects.equals(this.chartFileRef, v1HelmReleaseSpecValuesFrom.chartFileRef) &&
        Objects.equals(this.configMapKeyRef, v1HelmReleaseSpecValuesFrom.configMapKeyRef) &&
        Objects.equals(this.externalSourceRef, v1HelmReleaseSpecValuesFrom.externalSourceRef) &&
        Objects.equals(this.secretKeyRef, v1HelmReleaseSpecValuesFrom.secretKeyRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chartFileRef, configMapKeyRef, externalSourceRef, secretKeyRef);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1HelmReleaseSpecValuesFrom {\n");
    sb.append("    chartFileRef: ").append(toIndentedString(chartFileRef)).append("\n");
    sb.append("    configMapKeyRef: ").append(toIndentedString(configMapKeyRef)).append("\n");
    sb.append("    externalSourceRef: ").append(toIndentedString(externalSourceRef)).append("\n");
    sb.append("    secretKeyRef: ").append(toIndentedString(secretKeyRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

